Devise gem installed and setted up successfully
wolox-training/adl-rails pull request #4
Opened 2018-09-11 17:23 UTC by alanlamaswolox

## Summary
I installed and configured the devise gem, and created a new user in the postgres database

## Trello
https://trello.com/c/dpwjRwEH/9-9-instalar-configurar-devise-y-crear-user

2018-09-11 17:28 UTC, fedeest requested changes

2018-09-11 17:28 UTC, fedeest commented on config/database.yml
> +  #database: kick_development
?

2018-09-11 17:28 UTC, fedeest commented on config/database.yml
> +  #database: kick_development
You have the database name key repeated many times

2018-09-11 17:28 UTC, fedeest commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
You should erase the ones that you don't use.

In this case, you only need recoverable and rememberable

2018-09-11 17:30 UTC, nicozar95 commented on Gemfile
> +gem 'devise'
Please lock the version

2018-09-11 17:32 UTC, nicozar95 commented on db/migrate/20180911160324_devise_create_users.rb
> +      t.string :last_name, null: false, default: ""
Remove the default for `first_name` and `last_name`

2018-09-11 17:33 UTC, nicozar95 requested changes
Lock the devise version, remove the default on the migration and check on fede's review

2018-09-11 18:41 UTC, fedeest requested changes

2018-09-11 18:41 UTC, fedeest commented on db/migrate/20180911160324_devise_create_users.rb
> +      t.string :last_name, null: false
Oh, i forgot: if you add this here (null: false) you should also add a validation to the model the checks for this.

Check this: https://guides.rubyonrails.org/active_record_validations.html The validation that checks for `presence true`

2018-09-11 19:24 UTC, nicozar95 commented on app/models/user.rb
> +  validates :email, presence: true
add a new line between devise and validates

2018-09-11 19:25 UTC, nicozar95 commented on app/models/user.rb
> +  validates :encrypted_password, presence: true
Remove this validation, devise already does it

2018-09-11 19:26 UTC, nicozar95 requested changes
Just the last changes

2018-09-11 19:42 UTC, nicozar95 approved these changes
Greate work!!! :+1: :+1:

2018-09-12 18:13 UTC, fedeest approved these changes

2018-09-12 18:18 UTC, merged